export const ActionTypes = {
  //post
  POST_LOADING: "POST_LOADING",
  SET_POSTS: "SET_POSTS",
  POST_ERROR: "POST_ERROR",
  GET_POST_DETAIL: "GET_POST_DETAIL",
  // Comment
  ADD_COMMENT_POST: "ADD_COMMENT_POST",
  COMMENTS_LOADING: "COMMENTS_LOADING",
  COMMENTS_ERROR: "COMMENTS_ERROR",
  SET_COMMENTS_POST: "SET_COMMENTS_POST"
};
